model_path: model/model.pkl
feature_transformers_path: feature_transformers/feat_trans.pkl
model_cols: [applicant_location,
 applicant_location_mean_grpby_and_category_city,
 applicant_location_std_grpby_and_area,
 applicant_location_std_grpby_and_category,
 applicant_location_std_grpby_and_city,
 applicant_location_std_grpby_and_organization,
 category_fe,
 education,
 education_mean_grpby_and_category,
 education_std_grpby_and_area,
 education_std_grpby_and_category_city,
 english,
 gender_fe,
 max_salary,
 max_salary_mean_grpby_and_category_dow,
 max_salary_median_grpby_and_area,
 max_salary_median_grpby_and_category_city,
 min_salary_median_grpby_and_organization,
 min_salary_std_grpby_and_organization,
 num_openings,
 num_openings_std_grpby_and_area,
 num_openings_std_grpby_and_category_city,
 organization_fe]